# Generated by Django 4.2.2 on 2023-07-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("telephony", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="duration",
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="phone_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="telephony.virtualphonenumber",
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="recipient_num",
            field=models.CharField(max_length=14, verbose_name="Recipient number"),
        ),
        migrations.AlterField(
            model_name="virtualphonenumber",
            name="phone_num",
            field=models.CharField(
                max_length=14, unique=True, verbose_name="Phone number"
            ),
        ),
    ]
